# Generated by Django 4.0.3 on 2022-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=50)),
                ('Sclass', models.CharField(max_length=50)),
                ('SAge', models.IntegerField(null=True)),
            ],
        ),
    ]
