# Generated by Django 4.0.3 on 2022-03-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Sclass',
            new_name='SClass',
        ),
    ]
